version: '2'
services:
  web:
    build: .
    ports:
     - "80:80"
    volumes:
     - .:/var/www/html
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  firefox:
    image: selenium/node-firefox
    links:
      - hub
  chrome:
    image: selenium/node-chrome
    links:
      - hub