version: '2'
services:
  web:
    build: .
    ports:
     - "80:80"
    volumes:
     - .:/var/www/html
  selenium_hub:
      image: 'selenium/hub:latest'
      ports:
      - '4444:4444'

  selenium_node:
      image: 'selenium/node-firefox:latest'
      depends_on:
        - selenium_hub
      environment:
        HUB_PORT_4444_TCP_ADDR: selenium_hub